  workspace: /workspace
  project: ${.workspace}/projects/${app_name} 
  data: ${.workspace}/data
  log: ${.project}/logs
  tmp: ${.data}/tmp
  cache: ${.tmp}/.cache
  archive: ${.data}/archive
  runtime: ${hydra:runtime.cwd}
  model: ${.data}/models
  dataset: ${.data}/datasets
  # dataset_processed: ${.workspace}/datasets/processed
  corpus: ${.dataset}/corpus/ekorpkit