defaults:
  - _default
  - /pipeline/eval_columns: default

_target_: ekorpkit.io.fetch.ecos.ECOS
name: ecos
ecos_api_key: ${oc.env:ECOS_API_KEY,null}
series_id:
series_name:
start_date:
end_date:
value_column: value
pipeline:
  eval_columns:
    expressions:
