defaults:
  - default

loader: 
  _target_: ekorpkit.datasets.loader.load_local_datasets
  source_dir: ${dir.dataset}/source/${..category}/${.name}
  source_files:
  column_mapping:
  reader: 
    _target_: read_csv
