defaults:
  - default

postprocess:
  pretokenize:
    num_workers: 1
    mp_tokenizer:
      _target_: ekorpkit.models.tokenizer.MPTokenizer
      backend: mecab
      num_workers: ${..num_workers}
      normalize: true
      userdic_path:
    tokenize_func: 
      _target_: tokenize_dataframe
      text_key: text
    extract_func:
      text_key: text
      nouns_only: false
      noun_pos_filter: 
        - NNG
        - NNP
        - XSN
        - SL
        - XR
        - NNB
        - NR
      token_xpos_filter: 
        - SP
