# @package _global_
defaults:
  - override /task/func: topic

# task:
#   subtask: 
#   corpus: 
#   corpus_type: dataframe
#   corpus_filetype:
#   filename_pattern:
#   id_keys: 
#     - id 
#     - chunk_no
#   text_key: text
#   corpus_dir: 
#   output_dir: 
#   export_dir:
#   model_dir:
#   model_name: 
#   model_id: 
#   sample_types:
#     - train
#     - test
#     - exp
#   topic_names: 
#   merge_cols:
#     - id
#   topic_nums:  
#   num_samples_per_topic: 100
#   num_tests_per_topic: 20
#   num_exps_per_topic: 2
#   min_topic_ratio: 0.5
#   groupby_cols:
#     - corpus_filename
#     - id