_target_: ekorpkit.models.transformer.SimpleTrainerClassification
defaults:
  - default

model_class: classification
reprocess_input_data: True
overwrite_output_dir: True
sliding_window: True
max_seq_length: 64
num_train_epochs: 10
train_batch_size: 32
fp16: True
evaluate_during_training: True
num_labels: 
labels_list: ${oc.select:dataset.labels_list,}
cuda_device: 0
